resource_types:
- name: git-branches
  type: docker-image
  source:
    repository: vito/git-branches-resource

resources:
  - name: demo
    type: git-branches
    source:
      uri: https://github.com/diwakar-k/branch.git
jobs:
  - name: "test-pipeline"
    public: false
    plan:
      - get: demo
        trigger: true
      - task: check
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          inputs:
          - name: demo
          run:
            path: sh
            args:
            - -exc
            - |
              ls 
        
      #   file: demo/build/test.yml