resource_types:
- name: git-branches
  type: docker-image
  source:
    repository: vito/git-branches-resource

resources:
  - name: demo
    type: git-branches
    source:
      uri: https://github.com/diwakar-k/branch.git
jobs:
  - name: "test-pipeline"
    public: false
    plan:
      - get: demo
        trigger: true
      - task: check
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: rguichard/fly
              tag: latest
          inputs:
          - name: demo
          run:
            path: sh
            args:
            - -exc
            - |
              cd demo 
              ls
              export NEW_VERSIONS=$(cat branches)
              export OLD_VERSIONS=$(cat removed)
              fly -t tutorial login -c http://54.242.191.180:8080 -u test -p test
        
      #   file: demo/build/test.yml